name: Docker Image PR Verification

on:
  pull_request:
    branches:
      - "**"

env:
  REGISTRY: obswebsocketcommunity
  ARTIFACT: docker

jobs:
  verify-pr:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Build and Test/Verify image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push secured image to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.secured
          push: true
          tags: localhost:5000/${{ env.ARTIFACT }}:latest

      - name: Build and push unsecured image to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.unsecured
          push: true
          tags: localhost:5000/${{ env.ARTIFACT }}:latest-unsecured

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Verify the secured build
        run: |
          chmod +x verify_build.sh && ./verify_build.sh localhost:5000/${{ env.ARTIFACT }} latest

      - name: Verify the unsecured build
        run: |
          chmod +x verify_build.sh && ./verify_build.sh localhost:5000/${{ env.ARTIFACT }} latest-unsecured unsecured
