name: Docker Image PR Verification

on:
  pull_request:
    branches:
      - '**'

env:
  REGISTRY: tinatiel
  ARTIFACT: obswebsocket

jobs:
  verify-pr:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Build and Test/Verify image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: localhost:5000/${{ env.ARTIFACT }}:latest

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Verify the build
        run: |
          chmod +x verify_build.sh && ./verify_build.sh localhost:5000/${{ env.ARTIFACT }}
