name: Docker Image CI - Latest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the Repo
    - uses: actions/checkout@v2
    
    # Download the latest artifacts from Palakis
    - name: Download Palakis latest Ubuntu Build
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: main.yml # "CI Multiplatform Build"
        branch: master
        repo: Palakis/obs-websocket
        path: downloads
     
    # Extract the git hash info of the download
    - name: Extract prerelease info
      run: |
        input=$(ls -d downloads/*-Ubuntu64) && echo PRERELEASE=${input:10:7} >> $GITHUB_ENV
        
    - name: Display directory contents
      run: ls -R

    # Build the image
    - name: Build the Docker image
      run: |
        docker build . \
        --file Dockerfile \
        --tag latest \
        --tag /some/repo/obs-websocket:$(date +%s).${PRERELEASE}
